### ISSUE TITLE
Totals disappeared from LA Views too

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#14]
We can no longer see the LA total for each parameter

**Comment by slowe** [comment]
Related to issue #12

**Comment by slowe** [comment]
This should now be fixed.

I've also altered the bar charts so that the bars are split into two parts: a grey envelope showing the total for that Primary and a coloured part that shows the fraction of that Primary in that Local Authority. Hopefully that adds a little clarification about the numbers.

![Screenshot_2019-11-20 NorthernPowerGrid Future Energy Scenarios(1)](https://user-images.githubusercontent.com/299787/69245814-72af0600-0b9f-11ea-98dc-0af2249f6097.png)

**Comment by mary-black** [comment]
Looked at it last night - sorry to be late responding, we are flat out here. But I think it's great, thank you.
