### ISSUE TITLE
Change tab name from 'Northern Powergrid Future Energy Scenarios' to 'Northern Powergrid Net Zero Scenarios'

### ISSUE THREAD

**Issue by olivericketts** [odileeds/northern-powergrid#32]

**Comment by slowe** [comment]
@olivericketts I shall guess that this means the page <title> that appears in your browser's "tab" rather than an element in a page itself. The current titles are "Northern Powergrid Emerging Thinking 2020" (map) and "Northern Powergrid Future Energy Scenarios - 2020 Emerging Thinking" (graphs). So I shall change them to "Northern Powergrid Net Zero Scenarios" and "Northern Powergrid Net Zero Scenarios: graphs" respectively.

**Comment by olivericketts** [comment]
Sorry for not making clearer - yes you are correct. Perfect, thank you.
