### ISSUE TITLE
Make email address yourpowergrid@northernpowergrid.com bring up a mailbox

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#40]
I have asked people to email yourpowergrid@northernpowergrid.com in the text under the visualisation. I was not sure what it would do if I made it a hyperlink or if that is the right way to make it bring up a mailbox. If it is a good idea to make it do so, could one of you do the honours please, or tell me how to? Thanks, Mary.

**Comment by patricklake2** [comment]
Hi Mary, hope you're well.
Yes, generally email addresses on websites should be made hyperlinks - you can do this in the same way as a normal hyperlink with a slight difference shown below:

* 'Normal' hyperlink to a website:
```html
<a href="http://google.com">Google</a>
```
* Email address hyperlink:
```html
<a href="mailto:yourpowergrid@northernpowergrid.com">yourpowergrid@northernpowergrid.com</a>
```
The '**mailto:**' bit is the bit that tells the browser that clicking the link should try and open an email client.

It's generally a good idea to still display the email address as text (as shown above) so that people have the option to just copy and paste it, because not every user will have an email client installed.

If you feel comfortable doing it and have the time, then go for it - we can check it after although I think you'll be fine - it looks like you've become pretty good with HTML and Git! 
Equally, if you'd like us to do it, that's no problem at all, just let us know.

Thanks,
Patrick

**Comment by slowe** [comment]
@mary-black I've added the link to start a new email (just as @patricklake2 mentions above). I also made it add a subject line of "2020 Emerging Thinking". Give it a try and close this if you are happy.
