### ISSUE TITLE
Net Zero Early not calculating the EVs correctly

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#53]
After mapping in new EV csv files the total EVs have correctly changed for all scenarios except Net Zero Early. Is this something to do with the name change? It says there are 17K EVs in 2030 when the csv file totals 174,173K

**Comment by mary-black** [comment]
Whoops - I mean there should be over 1.5m. It may be the "In Year" scale that isn't working properly.

**Comment by slowe** [comment]
@mary-black When you say "the total EVs have correctly changed for all scenarios except Net Zero Early" what are you referring to? For 2030, the in-year scale goes up to 17,000 because the Local Authority with the highest number is Leeds with 16,202. The highest Primary in Leeds in 2030 is FIR TREE LANE with 569. However I've just noticed that you've updated the file so perhaps that was the problem.

**Comment by slowe** [comment]
Updating to the new file, I see that Leeds in 2030 now totals 173,751.

**Comment by mary-black** [comment]
Yes all working ok. I think I also has a caching issue not seeing the update after I pushed another updated file. Once I knew you could see the higher numbers I closed and reopened Chrome and all was well.
So I am comfortable about our new csv formats working. I will test a graphs example later too, once I have time again for the tool.
